### ISSUE TITLE
Add your solution!

### ISSUE THREAD

**Issue by NLDev** [NLDev/Hacktoberfest-2020-FizzBuzz#3]
<p align="center">
<b>:jack_o_lantern: Hacktoberfest 2020 FizzBuzz</b><br>
<img height="150" width="auto" src="https://i.imgur.com/5RJIOwI.png" />
</p>

<h4 align="center">Please consult <a href="https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/master/README.md">the ReadMe</a> for information on what this repository is about and how to contribute!</h4>

<hr>

# :exclamation: READ BEFORE CONTRIBUTING
**THIS REPOSITORY IS IN COMPLIANCE WITH THE HACKTOBERFEST VALUES AND RULES:** <br>
We cannot and **will not** accept every PR and label invalid one's accordingly! Examples are off-topic contributions, duplicated solutions, copy-paste solutions as well as obvious +1 attempts. <br>
We are searching for **interesting/creative/abstract/unique/extraordinary/weird** solutions to FizzBuzz. Only one _normal_ solution per language is permitted! <br>
This repository aligns with [the values of the Hacktoberfest](https://hacktoberfest.digitalocean.com/details) as it is meant as a fun challenge as well as a platform to learn (experiment with different solutions, challenging yourself to come up with creative solutions to a unique problem). <br>
**Denied PR's can be found [here](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/issues?q=label%3Ainvalid+is%3Aclosed)**.

<hr>

**Happy hacking!**

**Comment by jayadevvasudevan** [comment]
can i work on this???

**Comment by demaria11** [comment]
Let me in !!

**Comment by js0805** [comment]
Please assign me this.

**Comment by pankajmandal1996** [comment]
Request

**Comment by nandanhere** [comment]
Nice! I submitted a swift version of fizz buzz, could you check it out?

**Comment by pankajmandal1996** [comment]
Yes

**Comment by aniket786333** [comment]
Amazing platform for coding

**Comment by GhostUser** [comment]
Can you pls assign to me, I'll do it with well written code.

**Comment by veldakarimi** [comment]
I would like to work on this using python

**Comment by gittygupta** [comment]
i would like to work on this

**Comment by vikas981** [comment]
interesting lets do that

**Comment by akshat235** [comment]
Please assign me this. I would like to write it in Python

**Comment by gourab337** [comment]
Please assign me this... I would like to write it in C++

**Comment by GambhirPalak27** [comment]
I would like to work on this using C++.

**Comment by PrachiSinghal86** [comment]
I would like to work on this using C,C++,Python.

**Comment by rajat1401** [comment]
Hi @NLDev  , I have made a [PR](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/pull/65) of what I believe to be the simplest python solution to fizzbuzz as a part of Hacktoberfest 2020. Please review.

**Comment by veldakarimi** [comment]
I have added a one-liner using python lambda and map functions. 
Please review.

**Comment by gittygupta** [comment]
Please check my PR. It was the 1st single line solution

**Comment by ShobhitRathi** [comment]
making a function of this on python

**Comment by Moras-del** [comment]
Hello, I would like to work on this using kotlin/scala. Assign me please :).

**Comment by keerti2001** [comment]
Sir I have made a pull request after adding a folder for Cpp

**Comment by pnidhi26** [comment]
I would like to work in Python

**Comment by NLDev** [comment]
Just for clarification:
I wont assign this issue to anyone because everyone is welcome to contribute!
Cheers

**Comment by withlovedese** [comment]
can I please be assigned to this?

**Comment by withlovedese** [comment]
Can i please be assigned to this? I would like to work in Java!

**Comment by NLDev** [comment]
> Can i please be assigned to this? I would like to work in Java!

No. See [here](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/issues/3#issuecomment-702217535).

**Comment by jotagarciaz** [comment]
I will try to do it in Ruby

**Comment by hackbansu** [comment]
Added fizzbuzz with go routines #171

**Comment by mihrab34** [comment]
I would like to add my own solution in Ruby

**Comment by mihrab34** [comment]
I would like to work on this using Ruby one-liner

**Comment by JossJoestar** [comment]
Can I help? 
and with what language can I do it?

**Comment by NLDev** [comment]
> Can I help?
> and with what language can I do it?

@JossJoestar Any, as stated in the readme :)

**Comment by Moglten** [comment]
let me in, I give it a try.

**Comment by manavbhikadiya** [comment]
can i work on this project?

**Comment by ruthwik3690** [comment]
I can do this. Please let me in

**Comment by joe733** [comment]
@NLDev, I guess it will be good if this issue is `/pinned`

**Comment by vittesha** [comment]
I would like to contribute

**Comment by jjay075** [comment]
I would like to contribute, please let me in

**Comment by manitmaini** [comment]
I have solved the Problem, Please check it out #274

**Comment by shivamguptaram** [comment]
I would like to work on this using python

**Comment by behnood-eghbali** [comment]
I'd love to work on this repo with javascript :100:

**Comment by archit2216** [comment]
I would love to work on this with python😃

**Comment by AnushkaThakkar** [comment]
I would like to work on this using python.

**Comment by keikoro** [comment]
@NLDev, are you in all seriousness arguing that this repository is in the spirit of Hacktoberfest? Wow. IMO, you are clearly contributing to [hurting open source](https://blog.domenic.me/hacktoberfest/) by asking for random contributions that don't help anyone.

**Comment by NLDev** [comment]
@keikoro The link you provided argues that Hacktoberfest itself is hurting the OSS Community. 
Either way, yes. the repository is in alignment with [Hacktoberfest's values](https://hacktoberfest.digitalocean.com/details). Please read the participation rules as well as hacktoberfest's values before accusing me of such things. The hacktoberfest welcomes beginners as well as intermediate programmers and professionals. In contrast to other repositories where people only commit their name to a list or so (most of those repositories have already been flagged by the way) this repository here is is for people of any skillset to challenge themself. I put a lot of effort into reviewing every single PR on its own and label obvious +1 attempts, as well as duplicates and off-topic PR's as invalid. You can check out the list of invalid PR's here: https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/pulls?q=is%3Apr+is%3Aclosed+label%3Ainvalid

I'd also recommend consulting the ReadMe of the repository before making such claims. 

Cheers

**Comment by keikoro** [comment]
While your project may not go against Hacktoberfest's "values", it's clearly not an existing OS project but designed solely to accept Hacktoberfest-related PRs. The repo name alone says as much, no need to read the README.

So my point stands: your project is not in the _spirit_ of Hacktoberfest, which has always been about making open source better. It's not about getting people to submit their solutions for exercises, that's what Computer Sciences courses are for, it's about giving back to OS.

**Comment by keikoro** [comment]
But since you linked to the [official website](https://hacktoberfest.digitalocean.com/details): I wouldn't agree this project meets the fourth and last point in the "Quality Standards" section.

> Something that's clearly an attempt to simply +1 your pull request count for October.

Individual PRs might meet that requirement, and PRs are, in fact, what the section focuses on, but I'd argue that's a limited reading of the rules (or, if you will, a failing on Hacktoberfest's part to not spell this out more clearly for people who nitpick over words rather than overall meaning).

**Comment by NLDev** [comment]
> While your project may not go against Hacktoberfest's "values", it's clearly not an existing OS project but designed solely to accept Hacktoberfest-related PRs. The repo name alone says as much, no need to read the README.

This might have _been_ the "spirit" of Haktoberfest. However the website clearly states: 

```Hacktoberfest is open to everyone in our global community. Whether you’re a seasoned contributor or looking for projects to contribute to for the first time, you’re welcome to participate.```

Don't get me wrong. I know what you mean. Yes, the hacktoberfest is meant to support existing open source projects that need help. However, anyone is welcome to participate and this repository isn't hurting anyone. It's not like everyone would just contribute to "serious" open source project if this repository here wouldn't exist. 

> It's not about getting people to submit their solutions for exercises, that's what Computer Sciences courses are for, it's about giving back to OS.

Again, the website states the it's mean for learning as well. 

> But since you linked to the official website: I wouldn't agree this project meets the fourth and last point in the "Quality Standards" section. "Something that's clearly an attempt to simply +1 your pull request count for October."

As I said, I manually review every single PR and attempts to effortlessly +1 will be labeled as invalid. There have been a lot of creative solutions so far. For instance, someone wrote the first and only [FizzBuzz implementation in the esoteric language OMGROFL](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/blob/master/Omgrofl/FizzBuzz.omgrofl) with instructions on [how to build it](https://github.com/NLDev/Hacktoberfest-2020-FizzBuzz/pull/205). 

Sure, this doesn't do much for the poor OSS community. Still no need in taking the fun out of it. 

> Individual PRs might meet that requirement, and PRs are, in fact, what the section focuses on, but I'd argue that's a limited reading of the rules (or, if you will, a failing on Hacktoberfest's part to not spell this out more clearly for people who nitpick over words rather than overall meaning).

Thankfully, this isn't for you to decide.

Cheers.

**Comment by Atharv-Attri** [comment]
I'm on @NLDev side here

**Comment by keikoro** [comment]
Good on ya, I guess...

**Comment by dev348** [comment]
I will try@NLDev  it's opportunity to prove myself

**Comment by Ankancode123** [comment]
please assign this to me i will use python 3 to solve the aforesaid problem

**Comment by urmila-24** [comment]
i will use python 3 in this

**Comment by nikolatechie** [comment]
@NLDev I've added my solution using Segment Tree ( #456 ).

**Comment by NLDev** [comment]
Thank you for participating!
