### ISSUE TITLE
Quick Summary description and gif mismatch (README.md)

### ISSUE THREAD

**Issue by Trimankaur** [NLDev/Hacktoberfest-2020-FizzBuzz#389]
Quick summary:

> FizzBuzz is a program that prints the numbers from 1 to 100. But for multiples of three it prints “Fizz” instead of the number and for the multiples of five, it prints “Buzz”. For numbers which are multiples of both three and five it prints “FizzBuzz”.
<img height="300" width="auto" src="https://64.media.tumblr.com/098171eb6557f68cae65fdffe485abc4/tumblr_onha88HP0a1w0dccho1_1280.gif">

**The summary states that we need to print numbers from 1 to 100, but in the gif, the numbering starts from 0.** (′ʘ⌄ʘ‵)

**Comment by NLDev** [comment]
This is just a visual representation of the algorithm. Doesn't really matter if you start at 0 or 1. 
Thanks anyway :)
