### ISSUE TITLE
Automating movies and TV series search using python script

### ISSUE THREAD

**Issue by pyGitHub7** [NLDev/Hacktoberfest-2020-FizzBuzz#414]
IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.
This project is coded in python language and uses basics of python data structure - lists, OOPS and some basics of database.
Please assign.

**Comment by NLDev** [comment]
Are you serious?
